[package]
name = "configfs"
version = "0.1.0"
authors = ["jD91mZM2 <me@krake.one>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fuse = "0.3.1"
structopt = "0.3.3"
time = "0.1.42"
libc = "0.2.65"
